documents: './app/**/*.graphql'
schema:
  - 'https://graphql.contentful.com/content/v1/spaces/v1kazl7nd6vv/environments/master':
      headers:
        'Authorization': 'Bearer ua7edGKBMBvdZLon8l-UPGLwPXWgVob_ssQxzouGFzY'
