module.exports = {
  content: ['./app/**/*.{ts,tsx,js,jsx}'],
  theme: {
    extend: {
      lineClamp: {
        7: '7',
        8: '8',
        9: '9',
        10: '10',
      },
      typography: ({ theme }) => ({
        purple: {
          css: {
            '--tw-prose-body': theme('colors.stone[900]'),
            '--tw-prose-headings': theme('colors.purple[900]'),
            '--tw-prose-lead': theme('colors.purple[700]'),
            '--tw-prose-links': theme('colors.purple[900]'),
            '--tw-prose-bold': theme('colors.purple[900]'),
            '--tw-prose-counters': theme('colors.purple[600]'),
            '--tw-prose-bullets': theme('colors.purple[400]'),
            '--tw-prose-hr': theme('colors.purple[300]'),
            '--tw-prose-quotes': theme('colors.purple[900]'),
            '--tw-prose-quote-borders': theme('colors.purple[300]'),
            '--tw-prose-captions': theme('colors.stone[900]'),
            '--tw-prose-code': theme('colors.purple[900]'),
            '--tw-prose-pre-code': theme('colors.purple[100]'),
            '--tw-prose-pre-bg': theme('colors.purple[900]'),
            '--tw-prose-th-borders': theme('colors.purple[300]'),
            '--tw-prose-td-borders': theme('colors.purple[200]'),
            '--tw-prose-invert-body': theme('colors.purple[200]'),
            '--tw-prose-invert-headings': theme('colors.white'),
            '--tw-prose-invert-lead': theme('colors.purple[300]'),
            '--tw-prose-invert-links': theme('colors.white'),
            '--tw-prose-invert-bold': theme('colors.white'),
            '--tw-prose-invert-counters': theme('colors.purple[400]'),
            '--tw-prose-invert-bullets': theme('colors.purple[600]'),
            '--tw-prose-invert-hr': theme('colors.purple[700]'),
            '--tw-prose-invert-quotes': theme('colors.purple[100]'),
            '--tw-prose-invert-quote-borders': theme('colors.purple[700]'),
            '--tw-prose-invert-captions': theme('colors.purple[400]'),
            '--tw-prose-invert-code': theme('colors.white'),
            '--tw-prose-invert-pre-code': theme('colors.purple[300]'),
            '--tw-prose-invert-pre-bg': 'rgb(0 0 0 / 50%)',
            '--tw-prose-invert-th-borders': theme('colors.purple[600]'),
            '--tw-prose-invert-td-borders': theme('colors.purple[700]'),
          },
        },
      }),
      screens: {
        '@hover': { raw: '(hover: hover)' },
      },
    },
    fontFamily: {
      sans: [
        'Open Sans',
        'ui-sans-serif',
        'system-ui',
        '-apple-system',
        'BlinkMacSystemFont',
        'Segoe UI',
        'Roboto',
        'Helvetica Neue',
        'Arial',
        'Noto Sans',
        'sans-serif',
        'Apple Color Emoji',
        'Segoe UI Emoji',
        'Segoe UI Symbol',
        'Noto Color Emoji',
      ],
      serif: ['Gill Sans', 'ui-serif', 'Georgia', 'Cambria', 'Times New Roman', 'Times', 'serif'],
    },
  },
  plugins: [require('@tailwindcss/line-clamp'), require('@tailwindcss/typography')],
};
